controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_rotational_vel: 0.80
  min_in_place_rotational_vel: 0.3
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  acc_lim_x: 2
  acc_lim_th: 2.5
  holonomic_robot: false
