transform_tolerance: 0.50
obstacle_range: 2.5
max_obstacle_height: 2.0
raytrace_range: 3.0
robot_radius: 0.17
inscribed_radius: 0.25
circumscribed_radius: 0.25
inflation_radius: 0.55
observation_sources: base_scan
base_scan: {data_type: LaserScan, marking: true, clearing: true} 

