local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.15
  robot_radius: 0.2
  inflation_radius: 0.25
  transform_tolerance: 10.0
  observation_sources: base_scan
  base_scan: {data_type: LaserScan, expected_update_rate: 1.0, marking: true, clearing: true} 

