TrajectoryPlannerROS:
  max_vel_x: 0.40
  min_vel_x: 0.05
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.35
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  acc_lim_x: 2.0
  acc_lim_th: 2.0
  holonomic_robot: false
